default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/not-bored-tonight_development

test:
  <<: *default
  database: db/not-bored-tonight_test

production:
  <<: *default
  database: not-bored-tonight_production
  username: not-bored-tonight
  password: <%= ENV['NOT-BORED-TONIGHT_DATABASE_PASSWORD'] %>
